linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - depguard
    - gofmt
    - goimports
    - misspell
    - unparam
    - nakedret
    - prealloc
    - forbidigo

linters-settings:
  forbidigo:
    analyze-types: true
    forbid:
      - p: EventClient
        msg: "Direct access to the Event table is restricted. Use the EventStore or mark as okay with //nolint:forbidigo."

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/SURF-Innovatie/MORIS/ent/event"
            desc: "Usage of the event table is restricted. Explicitly mark as okay with //nolint:depguard if necessary."
          - pkg: "log"
            desc: "Use the logrus package instead of the standard library log package."
  goimports:
    local-prefixes: github.com/SURF-Innovatie/MORIS

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
