// Code generated by ent, DO NOT EDIT.

package projectstartedevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldDescription, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldEndDate, v))
}

// OrganisationID applies equality check predicate on the "organisation_id" field. It's identical to OrganisationIDEQ.
func OrganisationID(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldOrganisationID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldContainsFold(FieldDescription, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldEndDate, v))
}

// OrganisationIDEQ applies the EQ predicate on the "organisation_id" field.
func OrganisationIDEQ(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldEQ(FieldOrganisationID, v))
}

// OrganisationIDNEQ applies the NEQ predicate on the "organisation_id" field.
func OrganisationIDNEQ(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNEQ(FieldOrganisationID, v))
}

// OrganisationIDIn applies the In predicate on the "organisation_id" field.
func OrganisationIDIn(vs ...uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldIn(FieldOrganisationID, vs...))
}

// OrganisationIDNotIn applies the NotIn predicate on the "organisation_id" field.
func OrganisationIDNotIn(vs ...uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldNotIn(FieldOrganisationID, vs...))
}

// OrganisationIDGT applies the GT predicate on the "organisation_id" field.
func OrganisationIDGT(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGT(FieldOrganisationID, v))
}

// OrganisationIDGTE applies the GTE predicate on the "organisation_id" field.
func OrganisationIDGTE(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldGTE(FieldOrganisationID, v))
}

// OrganisationIDLT applies the LT predicate on the "organisation_id" field.
func OrganisationIDLT(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLT(FieldOrganisationID, v))
}

// OrganisationIDLTE applies the LTE predicate on the "organisation_id" field.
func OrganisationIDLTE(v uuid.UUID) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.FieldLTE(FieldOrganisationID, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectStartedEvent) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectStartedEvent) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectStartedEvent) predicate.ProjectStartedEvent {
	return predicate.ProjectStartedEvent(sql.NotPredicates(p))
}
