// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLanguage, v))
}

// Type applies equality check predicate on the "Type" field. It's identical to TypeEQ.
func Type(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldType, v))
}

// Doi applies equality check predicate on the "doi" field. It's identical to DoiEQ.
func Doi(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDoi, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldName, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldLanguage, v))
}

// TypeEQ applies the EQ predicate on the "Type" field.
func TypeEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "Type" field.
func TypeNEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "Type" field.
func TypeIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "Type" field.
func TypeNotIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "Type" field.
func TypeGT(v int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "Type" field.
func TypeGTE(v int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "Type" field.
func TypeLT(v int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "Type" field.
func TypeLTE(v int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "Type" field.
func TypeIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "Type" field.
func TypeNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldType))
}

// DoiEQ applies the EQ predicate on the "doi" field.
func DoiEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDoi, v))
}

// DoiNEQ applies the NEQ predicate on the "doi" field.
func DoiNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDoi, v))
}

// DoiIn applies the In predicate on the "doi" field.
func DoiIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDoi, vs...))
}

// DoiNotIn applies the NotIn predicate on the "doi" field.
func DoiNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDoi, vs...))
}

// DoiGT applies the GT predicate on the "doi" field.
func DoiGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDoi, v))
}

// DoiGTE applies the GTE predicate on the "doi" field.
func DoiGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDoi, v))
}

// DoiLT applies the LT predicate on the "doi" field.
func DoiLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDoi, v))
}

// DoiLTE applies the LTE predicate on the "doi" field.
func DoiLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDoi, v))
}

// DoiContains applies the Contains predicate on the "doi" field.
func DoiContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldDoi, v))
}

// DoiHasPrefix applies the HasPrefix predicate on the "doi" field.
func DoiHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldDoi, v))
}

// DoiHasSuffix applies the HasSuffix predicate on the "doi" field.
func DoiHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldDoi, v))
}

// DoiIsNil applies the IsNil predicate on the "doi" field.
func DoiIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldDoi))
}

// DoiNotNil applies the NotNil predicate on the "doi" field.
func DoiNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldDoi))
}

// DoiEqualFold applies the EqualFold predicate on the "doi" field.
func DoiEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldDoi, v))
}

// DoiContainsFold applies the ContainsFold predicate on the "doi" field.
func DoiContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldDoi, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
