// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/descriptionchangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
)

// DescriptionChangedEventDelete is the builder for deleting a DescriptionChangedEvent entity.
type DescriptionChangedEventDelete struct {
	config
	hooks    []Hook
	mutation *DescriptionChangedEventMutation
}

// Where appends a list predicates to the DescriptionChangedEventDelete builder.
func (_d *DescriptionChangedEventDelete) Where(ps ...predicate.DescriptionChangedEvent) *DescriptionChangedEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DescriptionChangedEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DescriptionChangedEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DescriptionChangedEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(descriptionchangedevent.Table, sqlgraph.NewFieldSpec(descriptionchangedevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DescriptionChangedEventDeleteOne is the builder for deleting a single DescriptionChangedEvent entity.
type DescriptionChangedEventDeleteOne struct {
	_d *DescriptionChangedEventDelete
}

// Where appends a list predicates to the DescriptionChangedEventDelete builder.
func (_d *DescriptionChangedEventDeleteOne) Where(ps ...predicate.DescriptionChangedEvent) *DescriptionChangedEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DescriptionChangedEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{descriptionchangedevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DescriptionChangedEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
