// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/enddatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/google/uuid"
)

// EndDateChangedEventCreate is the builder for creating a EndDateChangedEvent entity.
type EndDateChangedEventCreate struct {
	config
	mutation *EndDateChangedEventMutation
	hooks    []Hook
}

// SetEndDate sets the "end_date" field.
func (_c *EndDateChangedEventCreate) SetEndDate(v time.Time) *EndDateChangedEventCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EndDateChangedEventCreate) SetID(v uuid.UUID) *EndDateChangedEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EndDateChangedEventCreate) SetNillableID(v *uuid.UUID) *EndDateChangedEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_c *EndDateChangedEventCreate) SetEventID(id uuid.UUID) *EndDateChangedEventCreate {
	_c.mutation.SetEventID(id)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *EndDateChangedEventCreate) SetEvent(v *Event) *EndDateChangedEventCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the EndDateChangedEventMutation object of the builder.
func (_c *EndDateChangedEventCreate) Mutation() *EndDateChangedEventMutation {
	return _c.mutation
}

// Save creates the EndDateChangedEvent in the database.
func (_c *EndDateChangedEventCreate) Save(ctx context.Context) (*EndDateChangedEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EndDateChangedEventCreate) SaveX(ctx context.Context) *EndDateChangedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndDateChangedEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndDateChangedEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EndDateChangedEventCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := enddatechangedevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EndDateChangedEventCreate) check() error {
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "EndDateChangedEvent.end_date"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "EndDateChangedEvent.event"`)}
	}
	return nil
}

func (_c *EndDateChangedEventCreate) sqlSave(ctx context.Context) (*EndDateChangedEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EndDateChangedEventCreate) createSpec() (*EndDateChangedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &EndDateChangedEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enddatechangedevent.Table, sqlgraph.NewFieldSpec(enddatechangedevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(enddatechangedevent.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   enddatechangedevent.EventTable,
			Columns: []string{enddatechangedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_end_date_changed = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EndDateChangedEventCreateBulk is the builder for creating many EndDateChangedEvent entities in bulk.
type EndDateChangedEventCreateBulk struct {
	config
	err      error
	builders []*EndDateChangedEventCreate
}

// Save creates the EndDateChangedEvent entities in the database.
func (_c *EndDateChangedEventCreateBulk) Save(ctx context.Context) ([]*EndDateChangedEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EndDateChangedEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EndDateChangedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EndDateChangedEventCreateBulk) SaveX(ctx context.Context) []*EndDateChangedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndDateChangedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndDateChangedEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
