// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SURF-Innovatie/MORIS/ent/enddatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/google/uuid"
)

// EndDateChangedEvent is the model entity for the EndDateChangedEvent schema.
type EndDateChangedEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate time.Time `json:"end_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EndDateChangedEventQuery when eager-loading is set.
	Edges                  EndDateChangedEventEdges `json:"edges"`
	event_end_date_changed *uuid.UUID
	selectValues           sql.SelectValues
}

// EndDateChangedEventEdges holds the relations/edges for other nodes in the graph.
type EndDateChangedEventEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EndDateChangedEventEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EndDateChangedEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enddatechangedevent.FieldEndDate:
			values[i] = new(sql.NullTime)
		case enddatechangedevent.FieldID:
			values[i] = new(uuid.UUID)
		case enddatechangedevent.ForeignKeys[0]: // event_end_date_changed
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EndDateChangedEvent fields.
func (_m *EndDateChangedEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enddatechangedevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case enddatechangedevent.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = value.Time
			}
		case enddatechangedevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field event_end_date_changed", values[i])
			} else if value.Valid {
				_m.event_end_date_changed = new(uuid.UUID)
				*_m.event_end_date_changed = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EndDateChangedEvent.
// This includes values selected through modifiers, order, etc.
func (_m *EndDateChangedEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the EndDateChangedEvent entity.
func (_m *EndDateChangedEvent) QueryEvent() *EventQuery {
	return NewEndDateChangedEventClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this EndDateChangedEvent.
// Note that you need to call EndDateChangedEvent.Unwrap() before calling this method if this EndDateChangedEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EndDateChangedEvent) Update() *EndDateChangedEventUpdateOne {
	return NewEndDateChangedEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EndDateChangedEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EndDateChangedEvent) Unwrap() *EndDateChangedEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EndDateChangedEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EndDateChangedEvent) String() string {
	var builder strings.Builder
	builder.WriteString("EndDateChangedEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("end_date=")
	builder.WriteString(_m.EndDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EndDateChangedEvents is a parsable slice of EndDateChangedEvent.
type EndDateChangedEvents []*EndDateChangedEvent
