// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/descriptionchangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/enddatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/organisationchangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/personaddedevent"
	"github.com/SURF-Innovatie/MORIS/ent/personremovedevent"
	"github.com/SURF-Innovatie/MORIS/ent/projectstartedevent"
	"github.com/SURF-Innovatie/MORIS/ent/startdatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/titlechangedevent"
	"github.com/google/uuid"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *EventCreate) SetProjectID(v uuid.UUID) *EventCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *EventCreate) SetVersion(v int) *EventCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetType sets the "type" field.
func (_c *EventCreate) SetType(v string) *EventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *EventCreate) SetOccurredAt(v time.Time) *EventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableOccurredAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v uuid.UUID) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProjectStartedID sets the "project_started" edge to the ProjectStartedEvent entity by ID.
func (_c *EventCreate) SetProjectStartedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetProjectStartedID(id)
	return _c
}

// SetNillableProjectStartedID sets the "project_started" edge to the ProjectStartedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableProjectStartedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetProjectStartedID(*id)
	}
	return _c
}

// SetProjectStarted sets the "project_started" edge to the ProjectStartedEvent entity.
func (_c *EventCreate) SetProjectStarted(v *ProjectStartedEvent) *EventCreate {
	return _c.SetProjectStartedID(v.ID)
}

// SetTitleChangedID sets the "title_changed" edge to the TitleChangedEvent entity by ID.
func (_c *EventCreate) SetTitleChangedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetTitleChangedID(id)
	return _c
}

// SetNillableTitleChangedID sets the "title_changed" edge to the TitleChangedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableTitleChangedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetTitleChangedID(*id)
	}
	return _c
}

// SetTitleChanged sets the "title_changed" edge to the TitleChangedEvent entity.
func (_c *EventCreate) SetTitleChanged(v *TitleChangedEvent) *EventCreate {
	return _c.SetTitleChangedID(v.ID)
}

// SetDescriptionChangedID sets the "description_changed" edge to the DescriptionChangedEvent entity by ID.
func (_c *EventCreate) SetDescriptionChangedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetDescriptionChangedID(id)
	return _c
}

// SetNillableDescriptionChangedID sets the "description_changed" edge to the DescriptionChangedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableDescriptionChangedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetDescriptionChangedID(*id)
	}
	return _c
}

// SetDescriptionChanged sets the "description_changed" edge to the DescriptionChangedEvent entity.
func (_c *EventCreate) SetDescriptionChanged(v *DescriptionChangedEvent) *EventCreate {
	return _c.SetDescriptionChangedID(v.ID)
}

// SetStartDateChangedID sets the "start_date_changed" edge to the StartDateChangedEvent entity by ID.
func (_c *EventCreate) SetStartDateChangedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetStartDateChangedID(id)
	return _c
}

// SetNillableStartDateChangedID sets the "start_date_changed" edge to the StartDateChangedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableStartDateChangedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetStartDateChangedID(*id)
	}
	return _c
}

// SetStartDateChanged sets the "start_date_changed" edge to the StartDateChangedEvent entity.
func (_c *EventCreate) SetStartDateChanged(v *StartDateChangedEvent) *EventCreate {
	return _c.SetStartDateChangedID(v.ID)
}

// SetEndDateChangedID sets the "end_date_changed" edge to the EndDateChangedEvent entity by ID.
func (_c *EventCreate) SetEndDateChangedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetEndDateChangedID(id)
	return _c
}

// SetNillableEndDateChangedID sets the "end_date_changed" edge to the EndDateChangedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableEndDateChangedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetEndDateChangedID(*id)
	}
	return _c
}

// SetEndDateChanged sets the "end_date_changed" edge to the EndDateChangedEvent entity.
func (_c *EventCreate) SetEndDateChanged(v *EndDateChangedEvent) *EventCreate {
	return _c.SetEndDateChangedID(v.ID)
}

// SetOrganisationChangedID sets the "organisation_changed" edge to the OrganisationChangedEvent entity by ID.
func (_c *EventCreate) SetOrganisationChangedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetOrganisationChangedID(id)
	return _c
}

// SetNillableOrganisationChangedID sets the "organisation_changed" edge to the OrganisationChangedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillableOrganisationChangedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetOrganisationChangedID(*id)
	}
	return _c
}

// SetOrganisationChanged sets the "organisation_changed" edge to the OrganisationChangedEvent entity.
func (_c *EventCreate) SetOrganisationChanged(v *OrganisationChangedEvent) *EventCreate {
	return _c.SetOrganisationChangedID(v.ID)
}

// SetPersonAddedID sets the "person_added" edge to the PersonAddedEvent entity by ID.
func (_c *EventCreate) SetPersonAddedID(id int) *EventCreate {
	_c.mutation.SetPersonAddedID(id)
	return _c
}

// SetNillablePersonAddedID sets the "person_added" edge to the PersonAddedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillablePersonAddedID(id *int) *EventCreate {
	if id != nil {
		_c = _c.SetPersonAddedID(*id)
	}
	return _c
}

// SetPersonAdded sets the "person_added" edge to the PersonAddedEvent entity.
func (_c *EventCreate) SetPersonAdded(v *PersonAddedEvent) *EventCreate {
	return _c.SetPersonAddedID(v.ID)
}

// SetPersonRemovedID sets the "person_removed" edge to the PersonRemovedEvent entity by ID.
func (_c *EventCreate) SetPersonRemovedID(id uuid.UUID) *EventCreate {
	_c.mutation.SetPersonRemovedID(id)
	return _c
}

// SetNillablePersonRemovedID sets the "person_removed" edge to the PersonRemovedEvent entity by ID if the given value is not nil.
func (_c *EventCreate) SetNillablePersonRemovedID(id *uuid.UUID) *EventCreate {
	if id != nil {
		_c = _c.SetPersonRemovedID(*id)
	}
	return _c
}

// SetPersonRemoved sets the "person_removed" edge to the PersonRemovedEvent entity.
func (_c *EventCreate) SetPersonRemoved(v *PersonRemovedEvent) *EventCreate {
	return _c.SetPersonRemovedID(v.ID)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.OccurredAt(); !ok {
		v := event.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Event.project_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Event.version"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Event.type"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "Event.occurred_at"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(event.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(event.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(event.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if nodes := _c.mutation.ProjectStartedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.ProjectStartedTable,
			Columns: []string{event.ProjectStartedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectstartedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TitleChangedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.TitleChangedTable,
			Columns: []string{event.TitleChangedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(titlechangedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DescriptionChangedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.DescriptionChangedTable,
			Columns: []string{event.DescriptionChangedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(descriptionchangedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StartDateChangedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.StartDateChangedTable,
			Columns: []string{event.StartDateChangedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(startdatechangedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EndDateChangedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.EndDateChangedTable,
			Columns: []string{event.EndDateChangedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enddatechangedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganisationChangedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.OrganisationChangedTable,
			Columns: []string{event.OrganisationChangedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organisationchangedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PersonAddedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.PersonAddedTable,
			Columns: []string{event.PersonAddedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personaddedevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PersonRemovedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   event.PersonRemovedTable,
			Columns: []string{event.PersonRemovedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personremovedevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
