// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/descriptionchangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/enddatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/organisationchangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/personaddedevent"
	"github.com/SURF-Innovatie/MORIS/ent/personremovedevent"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/SURF-Innovatie/MORIS/ent/productaddedevent"
	"github.com/SURF-Innovatie/MORIS/ent/productremovedevent"
	"github.com/SURF-Innovatie/MORIS/ent/projectstartedevent"
	"github.com/SURF-Innovatie/MORIS/ent/startdatechangedevent"
	"github.com/SURF-Innovatie/MORIS/ent/titlechangedevent"
	"github.com/google/uuid"
)

// EventQuery is the builder for querying Event entities.
type EventQuery struct {
	config
	ctx                     *QueryContext
	order                   []event.OrderOption
	inters                  []Interceptor
	predicates              []predicate.Event
	withProjectStarted      *ProjectStartedEventQuery
	withTitleChanged        *TitleChangedEventQuery
	withDescriptionChanged  *DescriptionChangedEventQuery
	withStartDateChanged    *StartDateChangedEventQuery
	withEndDateChanged      *EndDateChangedEventQuery
	withOrganisationChanged *OrganisationChangedEventQuery
	withPersonAdded         *PersonAddedEventQuery
	withPersonRemoved       *PersonRemovedEventQuery
	withProductAdded        *ProductAddedEventQuery
	withProductRemoved      *ProductRemovedEventQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EventQuery builder.
func (_q *EventQuery) Where(ps ...predicate.Event) *EventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EventQuery) Limit(limit int) *EventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EventQuery) Offset(offset int) *EventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EventQuery) Unique(unique bool) *EventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EventQuery) Order(o ...event.OrderOption) *EventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProjectStarted chains the current query on the "project_started" edge.
func (_q *EventQuery) QueryProjectStarted() *ProjectStartedEventQuery {
	query := (&ProjectStartedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(projectstartedevent.Table, projectstartedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.ProjectStartedTable, event.ProjectStartedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTitleChanged chains the current query on the "title_changed" edge.
func (_q *EventQuery) QueryTitleChanged() *TitleChangedEventQuery {
	query := (&TitleChangedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(titlechangedevent.Table, titlechangedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.TitleChangedTable, event.TitleChangedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDescriptionChanged chains the current query on the "description_changed" edge.
func (_q *EventQuery) QueryDescriptionChanged() *DescriptionChangedEventQuery {
	query := (&DescriptionChangedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(descriptionchangedevent.Table, descriptionchangedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.DescriptionChangedTable, event.DescriptionChangedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStartDateChanged chains the current query on the "start_date_changed" edge.
func (_q *EventQuery) QueryStartDateChanged() *StartDateChangedEventQuery {
	query := (&StartDateChangedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(startdatechangedevent.Table, startdatechangedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.StartDateChangedTable, event.StartDateChangedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEndDateChanged chains the current query on the "end_date_changed" edge.
func (_q *EventQuery) QueryEndDateChanged() *EndDateChangedEventQuery {
	query := (&EndDateChangedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(enddatechangedevent.Table, enddatechangedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.EndDateChangedTable, event.EndDateChangedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganisationChanged chains the current query on the "organisation_changed" edge.
func (_q *EventQuery) QueryOrganisationChanged() *OrganisationChangedEventQuery {
	query := (&OrganisationChangedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(organisationchangedevent.Table, organisationchangedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.OrganisationChangedTable, event.OrganisationChangedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPersonAdded chains the current query on the "person_added" edge.
func (_q *EventQuery) QueryPersonAdded() *PersonAddedEventQuery {
	query := (&PersonAddedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(personaddedevent.Table, personaddedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.PersonAddedTable, event.PersonAddedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPersonRemoved chains the current query on the "person_removed" edge.
func (_q *EventQuery) QueryPersonRemoved() *PersonRemovedEventQuery {
	query := (&PersonRemovedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(personremovedevent.Table, personremovedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.PersonRemovedTable, event.PersonRemovedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProductAdded chains the current query on the "product_added" edge.
func (_q *EventQuery) QueryProductAdded() *ProductAddedEventQuery {
	query := (&ProductAddedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(productaddedevent.Table, productaddedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.ProductAddedTable, event.ProductAddedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProductRemoved chains the current query on the "product_removed" edge.
func (_q *EventQuery) QueryProductRemoved() *ProductRemovedEventQuery {
	query := (&ProductRemovedEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(event.Table, event.FieldID, selector),
			sqlgraph.To(productremovedevent.Table, productremovedevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, event.ProductRemovedTable, event.ProductRemovedColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Event entity from the query.
// Returns a *NotFoundError when no Event was found.
func (_q *EventQuery) First(ctx context.Context) (*Event, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{event.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EventQuery) FirstX(ctx context.Context) *Event {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Event ID from the query.
// Returns a *NotFoundError when no Event ID was found.
func (_q *EventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{event.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Event entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Event entity is found.
// Returns a *NotFoundError when no Event entities are found.
func (_q *EventQuery) Only(ctx context.Context) (*Event, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{event.Label}
	default:
		return nil, &NotSingularError{event.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EventQuery) OnlyX(ctx context.Context) *Event {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Event ID in the query.
// Returns a *NotSingularError when more than one Event ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{event.Label}
	default:
		err = &NotSingularError{event.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Events.
func (_q *EventQuery) All(ctx context.Context) ([]*Event, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Event, *EventQuery]()
	return withInterceptors[[]*Event](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EventQuery) AllX(ctx context.Context) []*Event {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Event IDs.
func (_q *EventQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(event.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EventQuery) Clone() *EventQuery {
	if _q == nil {
		return nil
	}
	return &EventQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]event.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.Event{}, _q.predicates...),
		withProjectStarted:      _q.withProjectStarted.Clone(),
		withTitleChanged:        _q.withTitleChanged.Clone(),
		withDescriptionChanged:  _q.withDescriptionChanged.Clone(),
		withStartDateChanged:    _q.withStartDateChanged.Clone(),
		withEndDateChanged:      _q.withEndDateChanged.Clone(),
		withOrganisationChanged: _q.withOrganisationChanged.Clone(),
		withPersonAdded:         _q.withPersonAdded.Clone(),
		withPersonRemoved:       _q.withPersonRemoved.Clone(),
		withProductAdded:        _q.withProductAdded.Clone(),
		withProductRemoved:      _q.withProductRemoved.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProjectStarted tells the query-builder to eager-load the nodes that are connected to
// the "project_started" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithProjectStarted(opts ...func(*ProjectStartedEventQuery)) *EventQuery {
	query := (&ProjectStartedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjectStarted = query
	return _q
}

// WithTitleChanged tells the query-builder to eager-load the nodes that are connected to
// the "title_changed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithTitleChanged(opts ...func(*TitleChangedEventQuery)) *EventQuery {
	query := (&TitleChangedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTitleChanged = query
	return _q
}

// WithDescriptionChanged tells the query-builder to eager-load the nodes that are connected to
// the "description_changed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithDescriptionChanged(opts ...func(*DescriptionChangedEventQuery)) *EventQuery {
	query := (&DescriptionChangedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDescriptionChanged = query
	return _q
}

// WithStartDateChanged tells the query-builder to eager-load the nodes that are connected to
// the "start_date_changed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithStartDateChanged(opts ...func(*StartDateChangedEventQuery)) *EventQuery {
	query := (&StartDateChangedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStartDateChanged = query
	return _q
}

// WithEndDateChanged tells the query-builder to eager-load the nodes that are connected to
// the "end_date_changed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithEndDateChanged(opts ...func(*EndDateChangedEventQuery)) *EventQuery {
	query := (&EndDateChangedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEndDateChanged = query
	return _q
}

// WithOrganisationChanged tells the query-builder to eager-load the nodes that are connected to
// the "organisation_changed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithOrganisationChanged(opts ...func(*OrganisationChangedEventQuery)) *EventQuery {
	query := (&OrganisationChangedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganisationChanged = query
	return _q
}

// WithPersonAdded tells the query-builder to eager-load the nodes that are connected to
// the "person_added" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithPersonAdded(opts ...func(*PersonAddedEventQuery)) *EventQuery {
	query := (&PersonAddedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPersonAdded = query
	return _q
}

// WithPersonRemoved tells the query-builder to eager-load the nodes that are connected to
// the "person_removed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithPersonRemoved(opts ...func(*PersonRemovedEventQuery)) *EventQuery {
	query := (&PersonRemovedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPersonRemoved = query
	return _q
}

// WithProductAdded tells the query-builder to eager-load the nodes that are connected to
// the "product_added" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithProductAdded(opts ...func(*ProductAddedEventQuery)) *EventQuery {
	query := (&ProductAddedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProductAdded = query
	return _q
}

// WithProductRemoved tells the query-builder to eager-load the nodes that are connected to
// the "product_removed" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EventQuery) WithProductRemoved(opts ...func(*ProductRemovedEventQuery)) *EventQuery {
	query := (&ProductRemovedEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProductRemoved = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Event.Query().
//		GroupBy(event.FieldProjectID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EventQuery) GroupBy(field string, fields ...string) *EventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = event.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//	}
//
//	client.Event.Query().
//		Select(event.FieldProjectID).
//		Scan(ctx, &v)
func (_q *EventQuery) Select(fields ...string) *EventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EventSelect{EventQuery: _q}
	sbuild.label = event.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EventSelect configured with the given aggregations.
func (_q *EventQuery) Aggregate(fns ...AggregateFunc) *EventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !event.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Event, error) {
	var (
		nodes       = []*Event{}
		_spec       = _q.querySpec()
		loadedTypes = [10]bool{
			_q.withProjectStarted != nil,
			_q.withTitleChanged != nil,
			_q.withDescriptionChanged != nil,
			_q.withStartDateChanged != nil,
			_q.withEndDateChanged != nil,
			_q.withOrganisationChanged != nil,
			_q.withPersonAdded != nil,
			_q.withPersonRemoved != nil,
			_q.withProductAdded != nil,
			_q.withProductRemoved != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Event).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Event{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProjectStarted; query != nil {
		if err := _q.loadProjectStarted(ctx, query, nodes, nil,
			func(n *Event, e *ProjectStartedEvent) { n.Edges.ProjectStarted = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTitleChanged; query != nil {
		if err := _q.loadTitleChanged(ctx, query, nodes, nil,
			func(n *Event, e *TitleChangedEvent) { n.Edges.TitleChanged = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDescriptionChanged; query != nil {
		if err := _q.loadDescriptionChanged(ctx, query, nodes, nil,
			func(n *Event, e *DescriptionChangedEvent) { n.Edges.DescriptionChanged = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStartDateChanged; query != nil {
		if err := _q.loadStartDateChanged(ctx, query, nodes, nil,
			func(n *Event, e *StartDateChangedEvent) { n.Edges.StartDateChanged = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEndDateChanged; query != nil {
		if err := _q.loadEndDateChanged(ctx, query, nodes, nil,
			func(n *Event, e *EndDateChangedEvent) { n.Edges.EndDateChanged = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrganisationChanged; query != nil {
		if err := _q.loadOrganisationChanged(ctx, query, nodes, nil,
			func(n *Event, e *OrganisationChangedEvent) { n.Edges.OrganisationChanged = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPersonAdded; query != nil {
		if err := _q.loadPersonAdded(ctx, query, nodes, nil,
			func(n *Event, e *PersonAddedEvent) { n.Edges.PersonAdded = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPersonRemoved; query != nil {
		if err := _q.loadPersonRemoved(ctx, query, nodes, nil,
			func(n *Event, e *PersonRemovedEvent) { n.Edges.PersonRemoved = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProductAdded; query != nil {
		if err := _q.loadProductAdded(ctx, query, nodes, nil,
			func(n *Event, e *ProductAddedEvent) { n.Edges.ProductAdded = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProductRemoved; query != nil {
		if err := _q.loadProductRemoved(ctx, query, nodes, nil,
			func(n *Event, e *ProductRemovedEvent) { n.Edges.ProductRemoved = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EventQuery) loadProjectStarted(ctx context.Context, query *ProjectStartedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *ProjectStartedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.ProjectStartedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.ProjectStartedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_project_started
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_project_started" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_project_started" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadTitleChanged(ctx context.Context, query *TitleChangedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *TitleChangedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.TitleChangedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.TitleChangedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_title_changed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_title_changed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_title_changed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadDescriptionChanged(ctx context.Context, query *DescriptionChangedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *DescriptionChangedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.DescriptionChangedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.DescriptionChangedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_description_changed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_description_changed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_description_changed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadStartDateChanged(ctx context.Context, query *StartDateChangedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *StartDateChangedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.StartDateChangedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.StartDateChangedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_start_date_changed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_start_date_changed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_start_date_changed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadEndDateChanged(ctx context.Context, query *EndDateChangedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *EndDateChangedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.EndDateChangedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.EndDateChangedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_end_date_changed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_end_date_changed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_end_date_changed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadOrganisationChanged(ctx context.Context, query *OrganisationChangedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *OrganisationChangedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.OrganisationChangedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.OrganisationChangedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_organisation_changed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_organisation_changed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_organisation_changed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadPersonAdded(ctx context.Context, query *PersonAddedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *PersonAddedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.PersonAddedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.PersonAddedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_person_added
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_person_added" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_person_added" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadPersonRemoved(ctx context.Context, query *PersonRemovedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *PersonRemovedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.PersonRemovedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.PersonRemovedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_person_removed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_person_removed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_person_removed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadProductAdded(ctx context.Context, query *ProductAddedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *ProductAddedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.ProductAddedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.ProductAddedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_product_added
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_product_added" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_product_added" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EventQuery) loadProductRemoved(ctx context.Context, query *ProductRemovedEventQuery, nodes []*Event, init func(*Event), assign func(*Event, *ProductRemovedEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Event)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.ProductRemovedEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(event.ProductRemovedColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.event_product_removed
		if fk == nil {
			return fmt.Errorf(`foreign-key "event_product_removed" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "event_product_removed" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for i := range fields {
			if fields[i] != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(event.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = event.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EventGroupBy is the group-by builder for Event entities.
type EventGroupBy struct {
	selector
	build *EventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EventGroupBy) Aggregate(fns ...AggregateFunc) *EventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventQuery, *EventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EventGroupBy) sqlScan(ctx context.Context, root *EventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EventSelect is the builder for selecting fields of Event entities.
type EventSelect struct {
	*EventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EventSelect) Aggregate(fns ...AggregateFunc) *EventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventQuery, *EventSelect](ctx, _s.EventQuery, _s, _s.inters, v)
}

func (_s *EventSelect) sqlScan(ctx context.Context, root *EventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
