// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/personremovedevent"
	"github.com/google/uuid"
)

// PersonRemovedEventCreate is the builder for creating a PersonRemovedEvent entity.
type PersonRemovedEventCreate struct {
	config
	mutation *PersonRemovedEventMutation
	hooks    []Hook
}

// SetPersonID sets the "person_id" field.
func (_c *PersonRemovedEventCreate) SetPersonID(v uuid.UUID) *PersonRemovedEventCreate {
	_c.mutation.SetPersonID(v)
	return _c
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_c *PersonRemovedEventCreate) SetNillablePersonID(v *uuid.UUID) *PersonRemovedEventCreate {
	if v != nil {
		_c.SetPersonID(*v)
	}
	return _c
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_c *PersonRemovedEventCreate) SetEventID(id uuid.UUID) *PersonRemovedEventCreate {
	_c.mutation.SetEventID(id)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *PersonRemovedEventCreate) SetEvent(v *Event) *PersonRemovedEventCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the PersonRemovedEventMutation object of the builder.
func (_c *PersonRemovedEventCreate) Mutation() *PersonRemovedEventMutation {
	return _c.mutation
}

// Save creates the PersonRemovedEvent in the database.
func (_c *PersonRemovedEventCreate) Save(ctx context.Context) (*PersonRemovedEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonRemovedEventCreate) SaveX(ctx context.Context) *PersonRemovedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonRemovedEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonRemovedEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonRemovedEventCreate) defaults() {
	if _, ok := _c.mutation.PersonID(); !ok {
		v := personremovedevent.DefaultPersonID()
		_c.mutation.SetPersonID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonRemovedEventCreate) check() error {
	if _, ok := _c.mutation.PersonID(); !ok {
		return &ValidationError{Name: "person_id", err: errors.New(`ent: missing required field "PersonRemovedEvent.person_id"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "PersonRemovedEvent.event"`)}
	}
	return nil
}

func (_c *PersonRemovedEventCreate) sqlSave(ctx context.Context) (*PersonRemovedEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonRemovedEventCreate) createSpec() (*PersonRemovedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &PersonRemovedEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(personremovedevent.Table, sqlgraph.NewFieldSpec(personremovedevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PersonID(); ok {
		_spec.SetField(personremovedevent.FieldPersonID, field.TypeUUID, value)
		_node.PersonID = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personremovedevent.EventTable,
			Columns: []string{personremovedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_person_removed = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PersonRemovedEventCreateBulk is the builder for creating many PersonRemovedEvent entities in bulk.
type PersonRemovedEventCreateBulk struct {
	config
	err      error
	builders []*PersonRemovedEventCreate
}

// Save creates the PersonRemovedEvent entities in the database.
func (_c *PersonRemovedEventCreateBulk) Save(ctx context.Context) ([]*PersonRemovedEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PersonRemovedEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonRemovedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonRemovedEventCreateBulk) SaveX(ctx context.Context) []*PersonRemovedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonRemovedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonRemovedEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
