// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/personaddedevent"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/google/uuid"
)

// PersonAddedEventUpdate is the builder for updating PersonAddedEvent entities.
type PersonAddedEventUpdate struct {
	config
	hooks    []Hook
	mutation *PersonAddedEventMutation
}

// Where appends a list predicates to the PersonAddedEventUpdate builder.
func (_u *PersonAddedEventUpdate) Where(ps ...predicate.PersonAddedEvent) *PersonAddedEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPersonID sets the "person_id" field.
func (_u *PersonAddedEventUpdate) SetPersonID(v uuid.UUID) *PersonAddedEventUpdate {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *PersonAddedEventUpdate) SetNillablePersonID(v *uuid.UUID) *PersonAddedEventUpdate {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetPersonName sets the "person_name" field.
func (_u *PersonAddedEventUpdate) SetPersonName(v string) *PersonAddedEventUpdate {
	_u.mutation.SetPersonName(v)
	return _u
}

// SetNillablePersonName sets the "person_name" field if the given value is not nil.
func (_u *PersonAddedEventUpdate) SetNillablePersonName(v *string) *PersonAddedEventUpdate {
	if v != nil {
		_u.SetPersonName(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PersonAddedEventUpdate) SetEventID(id uuid.UUID) *PersonAddedEventUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PersonAddedEventUpdate) SetEvent(v *Event) *PersonAddedEventUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the PersonAddedEventMutation object of the builder.
func (_u *PersonAddedEventUpdate) Mutation() *PersonAddedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PersonAddedEventUpdate) ClearEvent() *PersonAddedEventUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonAddedEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonAddedEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonAddedEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonAddedEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonAddedEventUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonAddedEvent.event"`)
	}
	return nil
}

func (_u *PersonAddedEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personaddedevent.Table, personaddedevent.Columns, sqlgraph.NewFieldSpec(personaddedevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PersonID(); ok {
		_spec.SetField(personaddedevent.FieldPersonID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PersonName(); ok {
		_spec.SetField(personaddedevent.FieldPersonName, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personaddedevent.EventTable,
			Columns: []string{personaddedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personaddedevent.EventTable,
			Columns: []string{personaddedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personaddedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonAddedEventUpdateOne is the builder for updating a single PersonAddedEvent entity.
type PersonAddedEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonAddedEventMutation
}

// SetPersonID sets the "person_id" field.
func (_u *PersonAddedEventUpdateOne) SetPersonID(v uuid.UUID) *PersonAddedEventUpdateOne {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *PersonAddedEventUpdateOne) SetNillablePersonID(v *uuid.UUID) *PersonAddedEventUpdateOne {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetPersonName sets the "person_name" field.
func (_u *PersonAddedEventUpdateOne) SetPersonName(v string) *PersonAddedEventUpdateOne {
	_u.mutation.SetPersonName(v)
	return _u
}

// SetNillablePersonName sets the "person_name" field if the given value is not nil.
func (_u *PersonAddedEventUpdateOne) SetNillablePersonName(v *string) *PersonAddedEventUpdateOne {
	if v != nil {
		_u.SetPersonName(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PersonAddedEventUpdateOne) SetEventID(id uuid.UUID) *PersonAddedEventUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PersonAddedEventUpdateOne) SetEvent(v *Event) *PersonAddedEventUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the PersonAddedEventMutation object of the builder.
func (_u *PersonAddedEventUpdateOne) Mutation() *PersonAddedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PersonAddedEventUpdateOne) ClearEvent() *PersonAddedEventUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the PersonAddedEventUpdate builder.
func (_u *PersonAddedEventUpdateOne) Where(ps ...predicate.PersonAddedEvent) *PersonAddedEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonAddedEventUpdateOne) Select(field string, fields ...string) *PersonAddedEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PersonAddedEvent entity.
func (_u *PersonAddedEventUpdateOne) Save(ctx context.Context) (*PersonAddedEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonAddedEventUpdateOne) SaveX(ctx context.Context) *PersonAddedEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonAddedEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonAddedEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonAddedEventUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonAddedEvent.event"`)
	}
	return nil
}

func (_u *PersonAddedEventUpdateOne) sqlSave(ctx context.Context) (_node *PersonAddedEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personaddedevent.Table, personaddedevent.Columns, sqlgraph.NewFieldSpec(personaddedevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonAddedEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personaddedevent.FieldID)
		for _, f := range fields {
			if !personaddedevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personaddedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PersonID(); ok {
		_spec.SetField(personaddedevent.FieldPersonID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PersonName(); ok {
		_spec.SetField(personaddedevent.FieldPersonName, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personaddedevent.EventTable,
			Columns: []string{personaddedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personaddedevent.EventTable,
			Columns: []string{personaddedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PersonAddedEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personaddedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
