// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/personremovedevent"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/google/uuid"
)

// PersonRemovedEventUpdate is the builder for updating PersonRemovedEvent entities.
type PersonRemovedEventUpdate struct {
	config
	hooks    []Hook
	mutation *PersonRemovedEventMutation
}

// Where appends a list predicates to the PersonRemovedEventUpdate builder.
func (_u *PersonRemovedEventUpdate) Where(ps ...predicate.PersonRemovedEvent) *PersonRemovedEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPersonID sets the "person_id" field.
func (_u *PersonRemovedEventUpdate) SetPersonID(v uuid.UUID) *PersonRemovedEventUpdate {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *PersonRemovedEventUpdate) SetNillablePersonID(v *uuid.UUID) *PersonRemovedEventUpdate {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PersonRemovedEventUpdate) SetEventID(id uuid.UUID) *PersonRemovedEventUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PersonRemovedEventUpdate) SetEvent(v *Event) *PersonRemovedEventUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the PersonRemovedEventMutation object of the builder.
func (_u *PersonRemovedEventUpdate) Mutation() *PersonRemovedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PersonRemovedEventUpdate) ClearEvent() *PersonRemovedEventUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonRemovedEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonRemovedEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonRemovedEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonRemovedEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonRemovedEventUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonRemovedEvent.event"`)
	}
	return nil
}

func (_u *PersonRemovedEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personremovedevent.Table, personremovedevent.Columns, sqlgraph.NewFieldSpec(personremovedevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PersonID(); ok {
		_spec.SetField(personremovedevent.FieldPersonID, field.TypeUUID, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personremovedevent.EventTable,
			Columns: []string{personremovedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personremovedevent.EventTable,
			Columns: []string{personremovedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personremovedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonRemovedEventUpdateOne is the builder for updating a single PersonRemovedEvent entity.
type PersonRemovedEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonRemovedEventMutation
}

// SetPersonID sets the "person_id" field.
func (_u *PersonRemovedEventUpdateOne) SetPersonID(v uuid.UUID) *PersonRemovedEventUpdateOne {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *PersonRemovedEventUpdateOne) SetNillablePersonID(v *uuid.UUID) *PersonRemovedEventUpdateOne {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *PersonRemovedEventUpdateOne) SetEventID(id uuid.UUID) *PersonRemovedEventUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *PersonRemovedEventUpdateOne) SetEvent(v *Event) *PersonRemovedEventUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the PersonRemovedEventMutation object of the builder.
func (_u *PersonRemovedEventUpdateOne) Mutation() *PersonRemovedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *PersonRemovedEventUpdateOne) ClearEvent() *PersonRemovedEventUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the PersonRemovedEventUpdate builder.
func (_u *PersonRemovedEventUpdateOne) Where(ps ...predicate.PersonRemovedEvent) *PersonRemovedEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonRemovedEventUpdateOne) Select(field string, fields ...string) *PersonRemovedEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PersonRemovedEvent entity.
func (_u *PersonRemovedEventUpdateOne) Save(ctx context.Context) (*PersonRemovedEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonRemovedEventUpdateOne) SaveX(ctx context.Context) *PersonRemovedEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonRemovedEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonRemovedEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonRemovedEventUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PersonRemovedEvent.event"`)
	}
	return nil
}

func (_u *PersonRemovedEventUpdateOne) sqlSave(ctx context.Context) (_node *PersonRemovedEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personremovedevent.Table, personremovedevent.Columns, sqlgraph.NewFieldSpec(personremovedevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonRemovedEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personremovedevent.FieldID)
		for _, f := range fields {
			if !personremovedevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personremovedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PersonID(); ok {
		_spec.SetField(personremovedevent.FieldPersonID, field.TypeUUID, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personremovedevent.EventTable,
			Columns: []string{personremovedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   personremovedevent.EventTable,
			Columns: []string{personremovedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PersonRemovedEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personremovedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
