// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/person"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/SURF-Innovatie/MORIS/ent/product"
	"github.com/google/uuid"
)

// PersonUpdate is the builder for updating Person entities.
type PersonUpdate struct {
	config
	hooks    []Hook
	mutation *PersonMutation
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdate) Where(ps ...predicate.Person) *PersonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PersonUpdate) SetUserID(v uuid.UUID) *PersonUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableUserID(v *uuid.UUID) *PersonUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PersonUpdate) ClearUserID() *PersonUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetOrcidID sets the "orcid_id" field.
func (_u *PersonUpdate) SetOrcidID(v string) *PersonUpdate {
	_u.mutation.SetOrcidID(v)
	return _u
}

// SetNillableOrcidID sets the "orcid_id" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableOrcidID(v *string) *PersonUpdate {
	if v != nil {
		_u.SetOrcidID(*v)
	}
	return _u
}

// ClearOrcidID clears the value of the "orcid_id" field.
func (_u *PersonUpdate) ClearOrcidID() *PersonUpdate {
	_u.mutation.ClearOrcidID()
	return _u
}

// SetName sets the "name" field.
func (_u *PersonUpdate) SetName(v string) *PersonUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableName(v *string) *PersonUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *PersonUpdate) SetGivenName(v string) *PersonUpdate {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableGivenName(v *string) *PersonUpdate {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// ClearGivenName clears the value of the "given_name" field.
func (_u *PersonUpdate) ClearGivenName() *PersonUpdate {
	_u.mutation.ClearGivenName()
	return _u
}

// SetFamilyName sets the "family_name" field.
func (_u *PersonUpdate) SetFamilyName(v string) *PersonUpdate {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "family_name" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableFamilyName(v *string) *PersonUpdate {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// ClearFamilyName clears the value of the "family_name" field.
func (_u *PersonUpdate) ClearFamilyName() *PersonUpdate {
	_u.mutation.ClearFamilyName()
	return _u
}

// SetEmail sets the "email" field.
func (_u *PersonUpdate) SetEmail(v string) *PersonUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableEmail(v *string) *PersonUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *PersonUpdate) AddProductIDs(ids ...uuid.UUID) *PersonUpdate {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *PersonUpdate) AddProducts(v ...*Product) *PersonUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdate) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *PersonUpdate) ClearProducts() *PersonUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *PersonUpdate) RemoveProductIDs(ids ...uuid.UUID) *PersonUpdate {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *PersonUpdate) RemoveProducts(v ...*Product) *PersonUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PersonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(person.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(person.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrcidID(); ok {
		_spec.SetField(person.FieldOrcidID, field.TypeString, value)
	}
	if _u.mutation.OrcidIDCleared() {
		_spec.ClearField(person.FieldOrcidID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(person.FieldGivenName, field.TypeString, value)
	}
	if _u.mutation.GivenNameCleared() {
		_spec.ClearField(person.FieldGivenName, field.TypeString)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(person.FieldFamilyName, field.TypeString, value)
	}
	if _u.mutation.FamilyNameCleared() {
		_spec.ClearField(person.FieldFamilyName, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(person.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonUpdateOne is the builder for updating a single Person entity.
type PersonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonMutation
}

// SetUserID sets the "user_id" field.
func (_u *PersonUpdateOne) SetUserID(v uuid.UUID) *PersonUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableUserID(v *uuid.UUID) *PersonUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PersonUpdateOne) ClearUserID() *PersonUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetOrcidID sets the "orcid_id" field.
func (_u *PersonUpdateOne) SetOrcidID(v string) *PersonUpdateOne {
	_u.mutation.SetOrcidID(v)
	return _u
}

// SetNillableOrcidID sets the "orcid_id" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableOrcidID(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetOrcidID(*v)
	}
	return _u
}

// ClearOrcidID clears the value of the "orcid_id" field.
func (_u *PersonUpdateOne) ClearOrcidID() *PersonUpdateOne {
	_u.mutation.ClearOrcidID()
	return _u
}

// SetName sets the "name" field.
func (_u *PersonUpdateOne) SetName(v string) *PersonUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableName(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGivenName sets the "given_name" field.
func (_u *PersonUpdateOne) SetGivenName(v string) *PersonUpdateOne {
	_u.mutation.SetGivenName(v)
	return _u
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableGivenName(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetGivenName(*v)
	}
	return _u
}

// ClearGivenName clears the value of the "given_name" field.
func (_u *PersonUpdateOne) ClearGivenName() *PersonUpdateOne {
	_u.mutation.ClearGivenName()
	return _u
}

// SetFamilyName sets the "family_name" field.
func (_u *PersonUpdateOne) SetFamilyName(v string) *PersonUpdateOne {
	_u.mutation.SetFamilyName(v)
	return _u
}

// SetNillableFamilyName sets the "family_name" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableFamilyName(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetFamilyName(*v)
	}
	return _u
}

// ClearFamilyName clears the value of the "family_name" field.
func (_u *PersonUpdateOne) ClearFamilyName() *PersonUpdateOne {
	_u.mutation.ClearFamilyName()
	return _u
}

// SetEmail sets the "email" field.
func (_u *PersonUpdateOne) SetEmail(v string) *PersonUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableEmail(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *PersonUpdateOne) AddProductIDs(ids ...uuid.UUID) *PersonUpdateOne {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *PersonUpdateOne) AddProducts(v ...*Product) *PersonUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdateOne) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *PersonUpdateOne) ClearProducts() *PersonUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *PersonUpdateOne) RemoveProductIDs(ids ...uuid.UUID) *PersonUpdateOne {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *PersonUpdateOne) RemoveProducts(v ...*Product) *PersonUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdateOne) Where(ps ...predicate.Person) *PersonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonUpdateOne) Select(field string, fields ...string) *PersonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Person entity.
func (_u *PersonUpdateOne) Save(ctx context.Context) (*Person, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdateOne) SaveX(ctx context.Context) *Person {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PersonUpdateOne) sqlSave(ctx context.Context) (_node *Person, err error) {
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Person.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, person.FieldID)
		for _, f := range fields {
			if !person.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != person.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(person.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(person.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrcidID(); ok {
		_spec.SetField(person.FieldOrcidID, field.TypeString, value)
	}
	if _u.mutation.OrcidIDCleared() {
		_spec.ClearField(person.FieldOrcidID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GivenName(); ok {
		_spec.SetField(person.FieldGivenName, field.TypeString, value)
	}
	if _u.mutation.GivenNameCleared() {
		_spec.ClearField(person.FieldGivenName, field.TypeString)
	}
	if value, ok := _u.mutation.FamilyName(); ok {
		_spec.SetField(person.FieldFamilyName, field.TypeString, value)
	}
	if _u.mutation.FamilyNameCleared() {
		_spec.ClearField(person.FieldFamilyName, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(person.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ProductsTable,
			Columns: person.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Person{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
