// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/productremovedevent"
	"github.com/google/uuid"
)

// ProductRemovedEvent is the model entity for the ProductRemovedEvent schema.
type ProductRemovedEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID uuid.UUID `json:"product_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductRemovedEventQuery when eager-loading is set.
	Edges                 ProductRemovedEventEdges `json:"edges"`
	event_product_removed *uuid.UUID
	selectValues          sql.SelectValues
}

// ProductRemovedEventEdges holds the relations/edges for other nodes in the graph.
type ProductRemovedEventEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductRemovedEventEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductRemovedEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productremovedevent.FieldID:
			values[i] = new(sql.NullInt64)
		case productremovedevent.FieldProductID:
			values[i] = new(uuid.UUID)
		case productremovedevent.ForeignKeys[0]: // event_product_removed
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductRemovedEvent fields.
func (_m *ProductRemovedEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productremovedevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case productremovedevent.FieldProductID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value != nil {
				_m.ProductID = *value
			}
		case productremovedevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field event_product_removed", values[i])
			} else if value.Valid {
				_m.event_product_removed = new(uuid.UUID)
				*_m.event_product_removed = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductRemovedEvent.
// This includes values selected through modifiers, order, etc.
func (_m *ProductRemovedEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the ProductRemovedEvent entity.
func (_m *ProductRemovedEvent) QueryEvent() *EventQuery {
	return NewProductRemovedEventClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this ProductRemovedEvent.
// Note that you need to call ProductRemovedEvent.Unwrap() before calling this method if this ProductRemovedEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProductRemovedEvent) Update() *ProductRemovedEventUpdateOne {
	return NewProductRemovedEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProductRemovedEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProductRemovedEvent) Unwrap() *ProductRemovedEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductRemovedEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProductRemovedEvent) String() string {
	var builder strings.Builder
	builder.WriteString("ProductRemovedEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteByte(')')
	return builder.String()
}

// ProductRemovedEvents is a parsable slice of ProductRemovedEvent.
type ProductRemovedEvents []*ProductRemovedEvent
