// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/SURF-Innovatie/MORIS/ent/projectstartedevent"
	"github.com/google/uuid"
)

// ProjectStartedEventUpdate is the builder for updating ProjectStartedEvent entities.
type ProjectStartedEventUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectStartedEventMutation
}

// Where appends a list predicates to the ProjectStartedEventUpdate builder.
func (_u *ProjectStartedEventUpdate) Where(ps ...predicate.ProjectStartedEvent) *ProjectStartedEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectStartedEventUpdate) SetTitle(v string) *ProjectStartedEventUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectStartedEventUpdate) SetNillableTitle(v *string) *ProjectStartedEventUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectStartedEventUpdate) SetDescription(v string) *ProjectStartedEventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectStartedEventUpdate) SetNillableDescription(v *string) *ProjectStartedEventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectStartedEventUpdate) SetStartDate(v time.Time) *ProjectStartedEventUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectStartedEventUpdate) SetNillableStartDate(v *time.Time) *ProjectStartedEventUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectStartedEventUpdate) SetEndDate(v time.Time) *ProjectStartedEventUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectStartedEventUpdate) SetNillableEndDate(v *time.Time) *ProjectStartedEventUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetOrganisationName sets the "organisation_name" field.
func (_u *ProjectStartedEventUpdate) SetOrganisationName(v string) *ProjectStartedEventUpdate {
	_u.mutation.SetOrganisationName(v)
	return _u
}

// SetNillableOrganisationName sets the "organisation_name" field if the given value is not nil.
func (_u *ProjectStartedEventUpdate) SetNillableOrganisationName(v *string) *ProjectStartedEventUpdate {
	if v != nil {
		_u.SetOrganisationName(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *ProjectStartedEventUpdate) SetEventID(id uuid.UUID) *ProjectStartedEventUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *ProjectStartedEventUpdate) SetEvent(v *Event) *ProjectStartedEventUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the ProjectStartedEventMutation object of the builder.
func (_u *ProjectStartedEventUpdate) Mutation() *ProjectStartedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *ProjectStartedEventUpdate) ClearEvent() *ProjectStartedEventUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectStartedEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectStartedEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectStartedEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectStartedEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectStartedEventUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectStartedEvent.event"`)
	}
	return nil
}

func (_u *ProjectStartedEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectstartedevent.Table, projectstartedevent.Columns, sqlgraph.NewFieldSpec(projectstartedevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(projectstartedevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(projectstartedevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(projectstartedevent.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(projectstartedevent.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganisationName(); ok {
		_spec.SetField(projectstartedevent.FieldOrganisationName, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectstartedevent.EventTable,
			Columns: []string{projectstartedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectstartedevent.EventTable,
			Columns: []string{projectstartedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectstartedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectStartedEventUpdateOne is the builder for updating a single ProjectStartedEvent entity.
type ProjectStartedEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectStartedEventMutation
}

// SetTitle sets the "title" field.
func (_u *ProjectStartedEventUpdateOne) SetTitle(v string) *ProjectStartedEventUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectStartedEventUpdateOne) SetNillableTitle(v *string) *ProjectStartedEventUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectStartedEventUpdateOne) SetDescription(v string) *ProjectStartedEventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectStartedEventUpdateOne) SetNillableDescription(v *string) *ProjectStartedEventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectStartedEventUpdateOne) SetStartDate(v time.Time) *ProjectStartedEventUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectStartedEventUpdateOne) SetNillableStartDate(v *time.Time) *ProjectStartedEventUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectStartedEventUpdateOne) SetEndDate(v time.Time) *ProjectStartedEventUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectStartedEventUpdateOne) SetNillableEndDate(v *time.Time) *ProjectStartedEventUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetOrganisationName sets the "organisation_name" field.
func (_u *ProjectStartedEventUpdateOne) SetOrganisationName(v string) *ProjectStartedEventUpdateOne {
	_u.mutation.SetOrganisationName(v)
	return _u
}

// SetNillableOrganisationName sets the "organisation_name" field if the given value is not nil.
func (_u *ProjectStartedEventUpdateOne) SetNillableOrganisationName(v *string) *ProjectStartedEventUpdateOne {
	if v != nil {
		_u.SetOrganisationName(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *ProjectStartedEventUpdateOne) SetEventID(id uuid.UUID) *ProjectStartedEventUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *ProjectStartedEventUpdateOne) SetEvent(v *Event) *ProjectStartedEventUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the ProjectStartedEventMutation object of the builder.
func (_u *ProjectStartedEventUpdateOne) Mutation() *ProjectStartedEventMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *ProjectStartedEventUpdateOne) ClearEvent() *ProjectStartedEventUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the ProjectStartedEventUpdate builder.
func (_u *ProjectStartedEventUpdateOne) Where(ps ...predicate.ProjectStartedEvent) *ProjectStartedEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectStartedEventUpdateOne) Select(field string, fields ...string) *ProjectStartedEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectStartedEvent entity.
func (_u *ProjectStartedEventUpdateOne) Save(ctx context.Context) (*ProjectStartedEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectStartedEventUpdateOne) SaveX(ctx context.Context) *ProjectStartedEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectStartedEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectStartedEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectStartedEventUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectStartedEvent.event"`)
	}
	return nil
}

func (_u *ProjectStartedEventUpdateOne) sqlSave(ctx context.Context) (_node *ProjectStartedEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectstartedevent.Table, projectstartedevent.Columns, sqlgraph.NewFieldSpec(projectstartedevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectStartedEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectstartedevent.FieldID)
		for _, f := range fields {
			if !projectstartedevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectstartedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(projectstartedevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(projectstartedevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(projectstartedevent.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(projectstartedevent.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganisationName(); ok {
		_spec.SetField(projectstartedevent.FieldOrganisationName, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectstartedevent.EventTable,
			Columns: []string{projectstartedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectstartedevent.EventTable,
			Columns: []string{projectstartedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectStartedEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectstartedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
