// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/projectstartedevent"
	"github.com/google/uuid"
)

// ProjectStartedEventCreate is the builder for creating a ProjectStartedEvent entity.
type ProjectStartedEventCreate struct {
	config
	mutation *ProjectStartedEventMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ProjectStartedEventCreate) SetTitle(v string) *ProjectStartedEventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProjectStartedEventCreate) SetDescription(v string) *ProjectStartedEventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *ProjectStartedEventCreate) SetStartDate(v time.Time) *ProjectStartedEventCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *ProjectStartedEventCreate) SetEndDate(v time.Time) *ProjectStartedEventCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetOrganisationID sets the "organisation_id" field.
func (_c *ProjectStartedEventCreate) SetOrganisationID(v uuid.UUID) *ProjectStartedEventCreate {
	_c.mutation.SetOrganisationID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectStartedEventCreate) SetID(v uuid.UUID) *ProjectStartedEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectStartedEventCreate) SetNillableID(v *uuid.UUID) *ProjectStartedEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_c *ProjectStartedEventCreate) SetEventID(id uuid.UUID) *ProjectStartedEventCreate {
	_c.mutation.SetEventID(id)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *ProjectStartedEventCreate) SetEvent(v *Event) *ProjectStartedEventCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the ProjectStartedEventMutation object of the builder.
func (_c *ProjectStartedEventCreate) Mutation() *ProjectStartedEventMutation {
	return _c.mutation
}

// Save creates the ProjectStartedEvent in the database.
func (_c *ProjectStartedEventCreate) Save(ctx context.Context) (*ProjectStartedEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectStartedEventCreate) SaveX(ctx context.Context) *ProjectStartedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectStartedEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectStartedEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectStartedEventCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := projectstartedevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectStartedEventCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ProjectStartedEvent.title"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProjectStartedEvent.description"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "ProjectStartedEvent.start_date"`)}
	}
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "ProjectStartedEvent.end_date"`)}
	}
	if _, ok := _c.mutation.OrganisationID(); !ok {
		return &ValidationError{Name: "organisation_id", err: errors.New(`ent: missing required field "ProjectStartedEvent.organisation_id"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "ProjectStartedEvent.event"`)}
	}
	return nil
}

func (_c *ProjectStartedEventCreate) sqlSave(ctx context.Context) (*ProjectStartedEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectStartedEventCreate) createSpec() (*ProjectStartedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectStartedEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectstartedevent.Table, sqlgraph.NewFieldSpec(projectstartedevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(projectstartedevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(projectstartedevent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(projectstartedevent.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(projectstartedevent.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.OrganisationID(); ok {
		_spec.SetField(projectstartedevent.FieldOrganisationID, field.TypeUUID, value)
		_node.OrganisationID = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectstartedevent.EventTable,
			Columns: []string{projectstartedevent.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_project_started = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectStartedEventCreateBulk is the builder for creating many ProjectStartedEvent entities in bulk.
type ProjectStartedEventCreateBulk struct {
	config
	err      error
	builders []*ProjectStartedEventCreate
}

// Save creates the ProjectStartedEvent entities in the database.
func (_c *ProjectStartedEventCreateBulk) Save(ctx context.Context) ([]*ProjectStartedEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectStartedEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectStartedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectStartedEventCreateBulk) SaveX(ctx context.Context) []*ProjectStartedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectStartedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectStartedEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
