// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SURF-Innovatie/MORIS/ent/predicate"
	"github.com/SURF-Innovatie/MORIS/ent/projectnotification"
)

// ProjectNotificationDelete is the builder for deleting a ProjectNotification entity.
type ProjectNotificationDelete struct {
	config
	hooks    []Hook
	mutation *ProjectNotificationMutation
}

// Where appends a list predicates to the ProjectNotificationDelete builder.
func (_d *ProjectNotificationDelete) Where(ps ...predicate.ProjectNotification) *ProjectNotificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProjectNotificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectNotificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProjectNotificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectnotification.Table, sqlgraph.NewFieldSpec(projectnotification.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProjectNotificationDeleteOne is the builder for deleting a single ProjectNotification entity.
type ProjectNotificationDeleteOne struct {
	_d *ProjectNotificationDelete
}

// Where appends a list predicates to the ProjectNotificationDelete builder.
func (_d *ProjectNotificationDeleteOne) Where(ps ...predicate.ProjectNotification) *ProjectNotificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProjectNotificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectnotification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProjectNotificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
