// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SURF-Innovatie/MORIS/ent/event"
	"github.com/SURF-Innovatie/MORIS/ent/titlechangedevent"
	"github.com/google/uuid"
)

// TitleChangedEvent is the model entity for the TitleChangedEvent schema.
type TitleChangedEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TitleChangedEventQuery when eager-loading is set.
	Edges               TitleChangedEventEdges `json:"edges"`
	event_title_changed *uuid.UUID
	selectValues        sql.SelectValues
}

// TitleChangedEventEdges holds the relations/edges for other nodes in the graph.
type TitleChangedEventEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TitleChangedEventEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TitleChangedEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case titlechangedevent.FieldTitle:
			values[i] = new(sql.NullString)
		case titlechangedevent.FieldID:
			values[i] = new(uuid.UUID)
		case titlechangedevent.ForeignKeys[0]: // event_title_changed
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TitleChangedEvent fields.
func (_m *TitleChangedEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case titlechangedevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case titlechangedevent.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case titlechangedevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field event_title_changed", values[i])
			} else if value.Valid {
				_m.event_title_changed = new(uuid.UUID)
				*_m.event_title_changed = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TitleChangedEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TitleChangedEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the TitleChangedEvent entity.
func (_m *TitleChangedEvent) QueryEvent() *EventQuery {
	return NewTitleChangedEventClient(_m.config).QueryEvent(_m)
}

// Update returns a builder for updating this TitleChangedEvent.
// Note that you need to call TitleChangedEvent.Unwrap() before calling this method if this TitleChangedEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TitleChangedEvent) Update() *TitleChangedEventUpdateOne {
	return NewTitleChangedEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TitleChangedEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TitleChangedEvent) Unwrap() *TitleChangedEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TitleChangedEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TitleChangedEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TitleChangedEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteByte(')')
	return builder.String()
}

// TitleChangedEvents is a parsable slice of TitleChangedEvent.
type TitleChangedEvents []*TitleChangedEvent
