// Code generated by gen/generator.go. DO NOT EDIT.

package events

import (
	"context"
	"errors"
	"fmt"

	"github.com/SURF-Innovatie/MORIS/internal/domain/entities"
	"github.com/google/uuid"
)

// --- ProductAdded / ProductRemoved ---

const ProductAddedType = "project.product_added"
const ProductRemovedType = "project.product_removed"

type ProductAdded struct {
	Base
	ProductID uuid.UUID `json:"product_id"`
}

func (ProductAdded) isEvent()     {}
func (ProductAdded) Type() string { return ProductAddedType }
func (e ProductAdded) String() string {
	return fmt.Sprintf("Product added: %s", e.ProductID)
}

func (e *ProductAdded) Apply(project *entities.Project) {
	project.ProductIDs = append(project.ProductIDs, e.ProductID)
}

func (e *ProductAdded) RelatedIDs() RelatedIDs {
	return RelatedIDs{ProductID: &e.ProductID}
}

func (e *ProductAdded) NotificationMessage() string {
	return "A new product has been added to the project."
}

func (e *ProductAdded) NotificationTemplate() string {
	return "Product '{{product.Name}}' was added to project '{{project.Title}}'"
}

func (e *ProductAdded) ApprovalRequestTemplate() string {
	return "Request to add product '{{product.Name}}' requires approval"
}

func (e *ProductAdded) ApprovedTemplate() string {
	return "Addition of product '{{product.Name}}' approved"
}

func (e *ProductAdded) RejectedTemplate() string {
	return "Addition of product '{{product.Name}}' rejected"
}

func (e *ProductAdded) NotificationVariables() map[string]string {
	return map[string]string{
		"event.ProductID": e.ProductID.String(),
	}
}

type ProductAddedInput struct {
	ProductID uuid.UUID `json:"product_id"`
}

func DecideProductAdded(
	projectID uuid.UUID,
	actor uuid.UUID,
	cur *entities.Project,
	in ProductAddedInput,
	status Status,
) (Event, error) {
	if projectID == uuid.Nil {
		return nil, errors.New("project id is required")
	}
	if in.ProductID == uuid.Nil {
		return nil, errors.New("product_id is required")
	}
	if cur == nil {
		return nil, errors.New("current project is required")
	}
	for _, x := range cur.ProductIDs {
		if x == in.ProductID {
			return nil, fmt.Errorf("product %s already exists", in.ProductID)
		}
	}
	base := NewBase(projectID, actor, status)
	base.FriendlyNameStr = ProductAddedMeta.FriendlyName

	return &ProductAdded{
		Base:      base,
		ProductID: in.ProductID,
	}, nil
}

var ProductAddedMeta = EventMeta{
	Type:         ProductAddedType,
	FriendlyName: "Product Addition",
}

// --- ProductRemoved ---

type ProductRemoved struct {
	Base
	ProductID uuid.UUID `json:"product_id"`
}

func (ProductRemoved) isEvent()     {}
func (ProductRemoved) Type() string { return ProductRemovedType }
func (e ProductRemoved) String() string {
	return fmt.Sprintf("Product removed: %s", e.ProductID)
}

func (e *ProductRemoved) Apply(project *entities.Project) {
	for i, x := range project.ProductIDs {
		if x == e.ProductID {
			project.ProductIDs = append(project.ProductIDs[:i], project.ProductIDs[i+1:]...)
			return
		}
	}
}

func (e *ProductRemoved) RelatedIDs() RelatedIDs {
	return RelatedIDs{ProductID: &e.ProductID}
}

func (e *ProductRemoved) NotificationMessage() string {
	return "A product has been removed from the project."
}

func (e *ProductRemoved) NotificationTemplate() string {
	return "Product '{{product.Name}}' was removed from project '{{project.Title}}'"
}

func (e *ProductRemoved) ApprovalRequestTemplate() string {
	return "Request to remove product '{{product.Name}}' requires approval"
}

func (e *ProductRemoved) ApprovedTemplate() string {
	return "Removal of product '{{product.Name}}' approved"
}

func (e *ProductRemoved) RejectedTemplate() string {
	return "Removal of product '{{product.Name}}' rejected"
}

func (e *ProductRemoved) NotificationVariables() map[string]string {
	return map[string]string{
		"event.ProductID": e.ProductID.String(),
	}
}

type ProductRemovedInput struct {
	ProductID uuid.UUID `json:"product_id"`
}

func DecideProductRemoved(
	projectID uuid.UUID,
	actor uuid.UUID,
	cur *entities.Project,
	in ProductRemovedInput,
	status Status,
) (Event, error) {
	if projectID == uuid.Nil {
		return nil, errors.New("project id is required")
	}
	if in.ProductID == uuid.Nil {
		return nil, errors.New("product_id is required")
	}
	if cur == nil {
		return nil, errors.New("current project is required")
	}
	found := false
	for _, x := range cur.ProductIDs {
		if x == in.ProductID {
			found = true
			break
		}
	}
	if !found {
		return nil, fmt.Errorf("product %s not found", in.ProductID)
	}
	base := NewBase(projectID, actor, status)
	base.FriendlyNameStr = ProductRemovedMeta.FriendlyName

	return &ProductRemoved{
		Base:      base,
		ProductID: in.ProductID,
	}, nil
}

var ProductRemovedMeta = EventMeta{
	Type:         ProductRemovedType,
	FriendlyName: "Product Removal",
}

func init() {
	RegisterMeta(ProductAddedMeta, func() Event {
		return &ProductAdded{Base: Base{FriendlyNameStr: ProductAddedMeta.FriendlyName}}
	})
	RegisterDecider[ProductAddedInput](ProductAddedType,
		func(ctx context.Context, projectID uuid.UUID, actor uuid.UUID, cur *entities.Project, in ProductAddedInput, status Status) (Event, error) {
			return DecideProductAdded(projectID, actor, cur, in, status)
		})
	RegisterInputType(ProductAddedType, ProductAddedInput{})

	RegisterMeta(ProductRemovedMeta, func() Event {
		return &ProductRemoved{Base: Base{FriendlyNameStr: ProductRemovedMeta.FriendlyName}}
	})
	RegisterDecider[ProductRemovedInput](ProductRemovedType,
		func(ctx context.Context, projectID uuid.UUID, actor uuid.UUID, cur *entities.Project, in ProductRemovedInput, status Status) (Event, error) {
			return DecideProductRemoved(projectID, actor, cur, in, status)
		})
	RegisterInputType(ProductRemovedType, ProductRemovedInput{})
}
