// This file is generated by apps/backend/cmd/codegen/main.go. DO NOT EDIT.
import customInstance from "./custom-axios";
import { PersonResponse, ProductResponse, ProjectRoleResponse } from "./generated-orval/model";

export type Datetime = string;

export enum ProjectEventType {

  ProductAdded = 'project.product_added',

  ProductRemoved = 'project.product_removed',

  TitleChanged = 'project.title_changed',

  DescriptionChanged = 'project.description_changed',

  StartDateChanged = 'project.start_date_changed',

  EndDateChanged = 'project.end_date_changed',

  RaidLinked = 'project.raid_linked',

  RaidUpdated = 'project.raid_updated',

  OwningOrgNodeChanged = 'project.owning_org_node_changed',

  ProjectStarted = 'project.started',

  CustomFieldValueSet = 'project.custom_field_value_set',

  EventPolicyAdded = 'project.event_policy_added',

  EventPolicyRemoved = 'project.event_policy_removed',

  EventPolicyUpdated = 'project.event_policy_updated',

  ProjectRoleAssigned = 'project.project_role_assigned',

  ProjectRoleUnassigned = 'project.role_unassigned',

}

// Base Event Interface
export interface BaseEvent {
  id: string;
  projectId: string;
  type: string;
  status: string;
  createdBy: string;
  at: Datetime;
  details: string;
  projectTitle: string;
  friendlyName?: string;
  personId?: string;
  productId?: string;
  projectRoleId?: string;
  orgNodeId?: string;
  person?: PersonResponse;
  product?: ProductResponse;
  projectRole?: ProjectRoleResponse;
  creator?: PersonResponse;
  data?: any;
}

// Specific Event Interfaces

export interface ProductAddedEvent extends BaseEvent {
  type: ProjectEventType.ProductAdded;
  data: ProductAddedInput;
}

export interface ProductRemovedEvent extends BaseEvent {
  type: ProjectEventType.ProductRemoved;
  data: ProductRemovedInput;
}

export interface TitleChangedEvent extends BaseEvent {
  type: ProjectEventType.TitleChanged;
  data: TitleChangedInput;
}

export interface DescriptionChangedEvent extends BaseEvent {
  type: ProjectEventType.DescriptionChanged;
  data: DescriptionChangedInput;
}

export interface StartDateChangedEvent extends BaseEvent {
  type: ProjectEventType.StartDateChanged;
  data: StartDateChangedInput;
}

export interface EndDateChangedEvent extends BaseEvent {
  type: ProjectEventType.EndDateChanged;
  data: EndDateChangedInput;
}

export interface RaidLinkedEvent extends BaseEvent {
  type: ProjectEventType.RaidLinked;
  data: RaidLinkedInput;
}

export interface RaidUpdatedEvent extends BaseEvent {
  type: ProjectEventType.RaidUpdated;
  data: RaidUpdatedInput;
}

export interface OwningOrgNodeChangedEvent extends BaseEvent {
  type: ProjectEventType.OwningOrgNodeChanged;
  data: OwningOrgNodeChangedInput;
}

export interface ProjectStartedEvent extends BaseEvent {
  type: ProjectEventType.ProjectStarted;
  data: ProjectStartedInput;
}

export interface CustomFieldValueSetEvent extends BaseEvent {
  type: ProjectEventType.CustomFieldValueSet;
  data: CustomFieldValueSetInput;
}

export interface EventPolicyAddedEvent extends BaseEvent {
  type: ProjectEventType.EventPolicyAdded;
  data: EventPolicyAddedInput;
}

export interface EventPolicyRemovedEvent extends BaseEvent {
  type: ProjectEventType.EventPolicyRemoved;
  data: EventPolicyRemovedInput;
}

export interface EventPolicyUpdatedEvent extends BaseEvent {
  type: ProjectEventType.EventPolicyUpdated;
  data: EventPolicyUpdatedInput;
}

export interface ProjectRoleAssignedEvent extends BaseEvent {
  type: ProjectEventType.ProjectRoleAssigned;
  data: ProjectRoleAssignedInput;
}

export interface ProjectRoleUnassignedEvent extends BaseEvent {
  type: ProjectEventType.ProjectRoleUnassigned;
  data: ProjectRoleUnassignedInput;
}


// Union Type
export type ProjectEvent =
  | ProductAddedEvent
  | ProductRemovedEvent
  | TitleChangedEvent
  | DescriptionChangedEvent
  | StartDateChangedEvent
  | EndDateChangedEvent
  | RaidLinkedEvent
  | RaidUpdatedEvent
  | OwningOrgNodeChangedEvent
  | ProjectStartedEvent
  | CustomFieldValueSetEvent
  | EventPolicyAddedEvent
  | EventPolicyRemovedEvent
  | EventPolicyUpdatedEvent
  | ProjectRoleAssignedEvent
  | ProjectRoleUnassignedEvent;

// Input Interfaces

export interface ProductAddedInput {
  product_id: string;
}

export const createProductAddedEvent = (projectId: string, input: ProductAddedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.product_added',
      input
    }
  });
};

export interface ProductRemovedInput {
  product_id: string;
}

export const createProductRemovedEvent = (projectId: string, input: ProductRemovedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.product_removed',
      input
    }
  });
};

export interface TitleChangedInput {
  title: string;
}

export const createTitleChangedEvent = (projectId: string, input: TitleChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.title_changed',
      input
    }
  });
};

export interface DescriptionChangedInput {
  description: string;
}

export const createDescriptionChangedEvent = (projectId: string, input: DescriptionChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.description_changed',
      input
    }
  });
};

export interface StartDateChangedInput {
  startDate: Datetime;
}

export const createStartDateChangedEvent = (projectId: string, input: StartDateChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.start_date_changed',
      input
    }
  });
};

export interface EndDateChangedInput {
  endDate: Datetime;
}

export const createEndDateChangedEvent = (projectId: string, input: EndDateChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.end_date_changed',
      input
    }
  });
};

export interface RaidLinkedInput {
  raid_info: RAiDInfo;
}

export const createRaidLinkedEvent = (projectId: string, input: RaidLinkedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.raid_linked',
      input
    }
  });
};

export interface RaidUpdatedInput {
  raid_info: RAiDInfo;
}

export const createRaidUpdatedEvent = (projectId: string, input: RaidUpdatedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.raid_updated',
      input
    }
  });
};

export interface OwningOrgNodeChangedInput {
  owning_org_node_id: string;
}

export const createOwningOrgNodeChangedEvent = (projectId: string, input: OwningOrgNodeChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.owning_org_node_changed',
      input
    }
  });
};

export interface ProjectStartedInput {
  title: string;
  description: string;
  start_date: Datetime;
  end_date: Datetime;
  members_ids: any[];
  owning_org_node_id: string;
}

export const createProjectStartedEvent = (projectId: string, input: ProjectStartedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.started',
      input
    }
  });
};

export interface CustomFieldValueSetInput {
  definition_id: string;
  value: string;
}

export const createCustomFieldValueSetEvent = (projectId: string, input: CustomFieldValueSetInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.custom_field_value_set',
      input
    }
  });
};

export interface EventPolicyAddedInput {
  name: string;
  description: string;
  event_types: string[];
  action_type: string;
  recipient_user_ids: any[];
  recipient_project_role_ids: any[];
  recipient_org_role_ids: any[];
  recipient_dynamic: string[];
  enabled: boolean;
}

export const createEventPolicyAddedEvent = (projectId: string, input: EventPolicyAddedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.event_policy_added',
      input
    }
  });
};

export interface EventPolicyRemovedInput {
  policy_id: string;
  name: string;
}

export const createEventPolicyRemovedEvent = (projectId: string, input: EventPolicyRemovedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.event_policy_removed',
      input
    }
  });
};

export interface EventPolicyUpdatedInput {
  policy_id: string;
  name: string;
  description: string;
  event_types: string[];
  action_type: string;
  recipient_user_ids: any[];
  recipient_project_role_ids: any[];
  recipient_org_role_ids: any[];
  recipient_dynamic: string[];
  enabled: boolean;
}

export const createEventPolicyUpdatedEvent = (projectId: string, input: EventPolicyUpdatedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.event_policy_updated',
      input
    }
  });
};

export interface ProjectRoleAssignedInput {
  person_id: string;
  project_role_id: string;
}

export const createProjectRoleAssignedEvent = (projectId: string, input: ProjectRoleAssignedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.project_role_assigned',
      input
    }
  });
};

export interface ProjectRoleUnassignedInput {
  person_id: string;
  project_role_id: string;
}

export const createProjectRoleUnassignedEvent = (projectId: string, input: ProjectRoleUnassignedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.role_unassigned',
      input
    }
  });
};


export interface RAiDInfo {
    raid_id: string;
    schema_uri: string;
    registration_agency_id: string;
    registration_agency_schema_uri: string;
    owner_id: string;
    owner_schema_uri: string;
    owner_service_point?: number;
    project_id: string;
    license: string;
    version: number;
    latest_sync?: string;
    dirty: boolean;
    checksum?: string;
}
