// This file is generated by apps/backend/cmd/codegen/main.go. DO NOT EDIT.
import customInstance from "./custom-axios";
import { PersonResponse, ProductResponse, ProjectRoleResponse } from "./generated-orval/model";

export type Datetime = string;

export enum ProjectEventType {

  EndDateChanged = 'project.end_date_changed',

  ProjectStarted = 'project.started',

  StartDateChanged = 'project.start_date_changed',

  TemplateEvent = 'project.template',

  DescriptionChanged = 'project.description_changed',

  OwningOrgNodeChanged = 'project.owning_org_node_changed',

  ProductRemoved = 'project.product_removed',

  ProductAdded = 'project.product_added',

  ProjectRoleAssigned = 'project.project_role_assigned',

  ProjectRoleUnassigned = 'project.role_unassigned',

  TitleChanged = 'project.title_changed',

}

// Base Event Interface
export interface BaseEvent {
  id: string;
  projectId: string;
  status: string;
  createdBy: string;
  at: Datetime;
  details: string;
  projectTitle: string;
  personId?: string;
  productId?: string;
  projectRoleId?: string;
  orgNodeId?: string;
  
  // Enriched Data
  person?: PersonResponse;
  product?: ProductResponse;
  projectRole?: ProjectRoleResponse;
}

// Specific Event Interfaces

export interface EndDateChangedEvent extends BaseEvent {
  type: ProjectEventType.EndDateChanged;
  data: EndDateChangedInput;
}

export interface ProjectStartedEvent extends BaseEvent {
  type: ProjectEventType.ProjectStarted;
  data: ProjectStartedInput;
}

export interface StartDateChangedEvent extends BaseEvent {
  type: ProjectEventType.StartDateChanged;
  data: StartDateChangedInput;
}

export interface TemplateEventEvent extends BaseEvent {
  type: ProjectEventType.TemplateEvent;
  data: TemplateEventInput;
}

export interface DescriptionChangedEvent extends BaseEvent {
  type: ProjectEventType.DescriptionChanged;
  data: DescriptionChangedInput;
}

export interface OwningOrgNodeChangedEvent extends BaseEvent {
  type: ProjectEventType.OwningOrgNodeChanged;
  data: OwningOrgNodeChangedInput;
}

export interface ProductRemovedEvent extends BaseEvent {
  type: ProjectEventType.ProductRemoved;
  data: ProductRemovedInput;
}

export interface ProductAddedEvent extends BaseEvent {
  type: ProjectEventType.ProductAdded;
  data: ProductAddedInput;
}

export interface ProjectRoleAssignedEvent extends BaseEvent {
  type: ProjectEventType.ProjectRoleAssigned;
  data: ProjectRoleAssignedInput;
}

export interface ProjectRoleUnassignedEvent extends BaseEvent {
  type: ProjectEventType.ProjectRoleUnassigned;
  data: ProjectRoleUnassignedInput;
}

export interface TitleChangedEvent extends BaseEvent {
  type: ProjectEventType.TitleChanged;
  data: TitleChangedInput;
}


// Union Type
export type ProjectEvent =
  | EndDateChangedEvent
  | ProjectStartedEvent
  | StartDateChangedEvent
  | TemplateEventEvent
  | DescriptionChangedEvent
  | OwningOrgNodeChangedEvent
  | ProductRemovedEvent
  | ProductAddedEvent
  | ProjectRoleAssignedEvent
  | ProjectRoleUnassignedEvent
  | TitleChangedEvent;

// Input Interfaces

export interface EndDateChangedInput {
  end_date: Datetime;
}

export const createEndDateChangedEvent = (projectId: string, input: EndDateChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.end_date_changed',
      input
    }
  });
};

export interface ProjectStartedInput {
  title: string;
  description: string;
  start_date: Datetime;
  end_date: Datetime;
  members_ids: any;
  owning_org_node_id: string;
}

export const createProjectStartedEvent = (projectId: string, input: ProjectStartedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.started',
      input
    }
  });
};

export interface StartDateChangedInput {
  start_date: Datetime;
}

export const createStartDateChangedEvent = (projectId: string, input: StartDateChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.start_date_changed',
      input
    }
  });
};

export interface TemplateEventInput {
  SomeStringField: string;
  SomeUUIDField: string;
}

export const createTemplateEventEvent = (projectId: string, input: TemplateEventInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.template',
      input
    }
  });
};

export interface DescriptionChangedInput {
  description: string;
}

export const createDescriptionChangedEvent = (projectId: string, input: DescriptionChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.description_changed',
      input
    }
  });
};

export interface OwningOrgNodeChangedInput {
  owning_org_node_id: string;
}

export const createOwningOrgNodeChangedEvent = (projectId: string, input: OwningOrgNodeChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.owning_org_node_changed',
      input
    }
  });
};

export interface ProductRemovedInput {
  product_id: string;
}

export const createProductRemovedEvent = (projectId: string, input: ProductRemovedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.product_removed',
      input
    }
  });
};

export interface ProductAddedInput {
  product_id: string;
}

export const createProductAddedEvent = (projectId: string, input: ProductAddedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.product_added',
      input
    }
  });
};

export interface ProjectRoleAssignedInput {
  person_id: string;
  project_role_id: string;
}

export const createProjectRoleAssignedEvent = (projectId: string, input: ProjectRoleAssignedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.project_role_assigned',
      input
    }
  });
};

export interface ProjectRoleUnassignedInput {
  person_id: string;
  project_role_id: string;
}

export const createProjectRoleUnassignedEvent = (projectId: string, input: ProjectRoleUnassignedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.role_unassigned',
      input
    }
  });
};

export interface TitleChangedInput {
  title: string;
}

export const createTitleChangedEvent = (projectId: string, input: TitleChangedInput) => {
  return customInstance<any>({
    url: `/projects/${projectId}/events`,
    method: 'POST',
    data: {
      projectId,
      type: 'project.title_changed',
      input
    }
  });
};

